Test change

diff --git a/.github/workflows/smoke-checks.yml b/.github/workflows/smoke-checks.yml
--- a/.github/workflows/smoke-checks.yml
+++ b/.github/workflows/smoke-checks.yml
@@ -30,242 +30,242 @@ jobs:
     runs-on: macos-15
     steps:
     - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/ruby-cache
-    - uses: ./.github/actions/xcode-cache
+    # - uses: ./.github/actions/ruby-cache
+    # - uses: ./.github/actions/xcode-cache
     - name: Build
-      run: bundle exec fastlane build_test_app_and_frameworks
-      timeout-minutes: 60
-    - uses: actions/upload-artifact@v4
-      if: success()
-      with:
-        name: cache-derived-data
-        path: |
-          derived_data/Build/**/*.app
-          derived_data/Build/**/*.xctestrun
-          derived_data/Build/**/*.framework
+      run: echo $GITHUB_BASE_REF
+  #     timeout-minutes: 60
+  #   - uses: actions/upload-artifact@v4
+  #     if: success()
+  #     with:
+  #       name: cache-derived-data
+  #       path: |
+  #         derived_data/Build/**/*.app
+  #         derived_data/Build/**/*.xctestrun
+  #         derived_data/Build/**/*.framework
 
-  automated-code-review:
-    name: Automated Code Review
-    runs-on: macos-14
-    env:
-      XCODE_VERSION: "15.4"
-    if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    steps:
-      - uses: actions/checkout@v4.1.1
-      - uses: ./.github/actions/bootstrap
-        env:
-          INSTALL_INTERFACE_ANALYZER: true
-      - run: bundle exec fastlane lint_pr
-      - run: bundle exec fastlane rubocop
-      - run: bundle exec fastlane run_swift_format strict:true
-      - run: bundle exec fastlane validate_public_interface
+  # automated-code-review:
+  #   name: Automated Code Review
+  #   runs-on: macos-14
+  #   env:
+  #     XCODE_VERSION: "15.4"
+  #   if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   steps:
+  #     - uses: actions/checkout@v4.1.1
+  #     - uses: ./.github/actions/bootstrap
+  #       env:
+  #         INSTALL_INTERFACE_ANALYZER: true
+  #     - run: bundle exec fastlane lint_pr
+  #     - run: bundle exec fastlane rubocop
+  #     - run: bundle exec fastlane run_swift_format strict:true
+  #     - run: bundle exec fastlane validate_public_interface
 
-  build-old-xcode:
-    name: Build LLC + UI (Xcode 15)
-    runs-on: macos-15
-    # if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    if: false # disable Xcode 15 builds
-    env:
-      XCODE_VERSION: "15.4"
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/ruby-cache
-    - name: List Xcode versions
-      run: mdfind "kMDItemCFBundleIdentifier = 'com.apple.dt.Xcode'"
-    - name: Build LLC
-      run: bundle exec fastlane test device:"iPhone 13" build_for_testing:true
-      timeout-minutes: 25
-    - name: Build UI
-      run: bundle exec fastlane test_ui device:"iPhone 13" build_for_testing:true
-      timeout-minutes: 25
+  # build-old-xcode:
+  #   name: Build LLC + UI (Xcode 15)
+  #   runs-on: macos-15
+  #   # if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   if: false # disable Xcode 15 builds
+  #   env:
+  #     XCODE_VERSION: "15.4"
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: ./.github/actions/ruby-cache
+  #   - name: List Xcode versions
+  #     run: mdfind "kMDItemCFBundleIdentifier = 'com.apple.dt.Xcode'"
+  #   - name: Build LLC
+  #     run: bundle exec fastlane test device:"iPhone 13" build_for_testing:true
+  #     timeout-minutes: 25
+  #   - name: Build UI
+  #     run: bundle exec fastlane test_ui device:"iPhone 13" build_for_testing:true
+  #     timeout-minutes: 25
 
-  test-llc-debug:
-    name: Test LLC (Debug)
-    runs-on: macos-15
-    if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-      with:
-        fetch-depth: 100
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_YEETD: true
-        INSTALL_SONAR: true
-    - name: Run LLC Tests (Debug)
-      run: bundle exec fastlane test device:"${{ env.IOS_SIMULATOR_DEVICE }}"
-      timeout-minutes: 60
-    - name: Run Sonar analysis
-      run: bundle exec fastlane sonar_upload
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        PR_NUMBER: ${{ github.event.number }}
-    - name: Parse xcresult
-      if: failure()
-      run: |
-        brew install chargepoint/xcparse/xcparse
-        xcparse logs fastlane/test_output/StreamChat.xcresult fastlane/test_output/logs/
-    - uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: Test Data LLC
-        path: |
-          fastlane/test_output/logs/*/Diagnostics/**/*.txt
-          fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
-    - name: Upload Test Coverage
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-coverage-${{ github.event.pull_request.number }}
-        path: reports/sonarqube-generic-coverage.xml
+  # test-llc-debug:
+  #   name: Test LLC (Debug)
+  #   runs-on: macos-15
+  #   if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #     with:
+  #       fetch-depth: 100
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_YEETD: true
+  #       INSTALL_SONAR: true
+  #   - name: Run LLC Tests (Debug)
+  #     run: bundle exec fastlane test device:"${{ env.IOS_SIMULATOR_DEVICE }}"
+  #     timeout-minutes: 60
+  #   - name: Run Sonar analysis
+  #     run: bundle exec fastlane sonar_upload
+  #     env:
+  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       PR_NUMBER: ${{ github.event.number }}
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: |
+  #       brew install chargepoint/xcparse/xcparse
+  #       xcparse logs fastlane/test_output/StreamChat.xcresult fastlane/test_output/logs/
+  #   - uses: actions/upload-artifact@v4
+  #     if: failure()
+  #     with:
+  #       name: Test Data LLC
+  #       path: |
+  #         fastlane/test_output/logs/*/Diagnostics/**/*.txt
+  #         fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
+  #   - name: Upload Test Coverage
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: test-coverage-${{ github.event.pull_request.number }}
+  #       path: reports/sonarqube-generic-coverage.xml
 
-  test-ui-debug:
-    name: Test UI (Debug)
-    runs-on: macos-15
-    needs: build-test-app-and-frameworks
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: actions/download-artifact@v4
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_YEETD: true
-        SKIP_SWIFT_BOOTSTRAP: true
-    - name: Run UI Tests (Debug)
-      run: bundle exec fastlane test_ui device:"${{ env.IOS_SIMULATOR_DEVICE }}" skip_build:true record:"${{ github.event.inputs.record_snapshots }}"
-      timeout-minutes: 120
-      env:
-        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }} # to open a PR
-        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # to use github cli
-    - name: Parse xcresult
-      if: failure()
-      run: |
-        brew install chargepoint/xcparse/xcparse
-        xcparse screenshots fastlane/test_output/StreamChatUI.xcresult fastlane/test_output/snapshots --test
-    - uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: Test Data UIKit
-        path: |
-          fastlane/test_output/snapshots
+  # test-ui-debug:
+  #   name: Test UI (Debug)
+  #   runs-on: macos-15
+  #   needs: build-test-app-and-frameworks
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_YEETD: true
+  #       SKIP_SWIFT_BOOTSTRAP: true
+  #   - name: Run UI Tests (Debug)
+  #     run: bundle exec fastlane test_ui device:"${{ env.IOS_SIMULATOR_DEVICE }}" skip_build:true record:"${{ github.event.inputs.record_snapshots }}"
+  #     timeout-minutes: 120
+  #     env:
+  #       GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }} # to open a PR
+  #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # to use github cli
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: |
+  #       brew install chargepoint/xcparse/xcparse
+  #       xcparse screenshots fastlane/test_output/StreamChatUI.xcresult fastlane/test_output/snapshots --test
+  #   - uses: actions/upload-artifact@v4
+  #     if: failure()
+  #     with:
+  #       name: Test Data UIKit
+  #       path: |
+  #         fastlane/test_output/snapshots
 
-  allure_testops_launch:
-    name: Launch Allure TestOps
-    runs-on: macos-15
-    if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    needs: build-test-app-and-frameworks
-    outputs:
-      launch_id: ${{ steps.get_launch_id.outputs.launch_id }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: ./.github/actions/ruby-cache
-    - name: Launch Allure TestOps
-      run: bundle exec fastlane allure_launch
-      env:
-        ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-        GITHUB_EVENT: ${{ toJson(github.event) }}
-    - id: get_launch_id
-      run: echo "launch_id=${{env.LAUNCH_ID}}" >> $GITHUB_OUTPUT
-      if: env.LAUNCH_ID != ''
+  # allure_testops_launch:
+  #   name: Launch Allure TestOps
+  #   runs-on: macos-15
+  #   if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   needs: build-test-app-and-frameworks
+  #   outputs:
+  #     launch_id: ${{ steps.get_launch_id.outputs.launch_id }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: ./.github/actions/ruby-cache
+  #   - name: Launch Allure TestOps
+  #     run: bundle exec fastlane allure_launch
+  #     env:
+  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #       GITHUB_EVENT: ${{ toJson(github.event) }}
+  #   - id: get_launch_id
+  #     run: echo "launch_id=${{env.LAUNCH_ID}}" >> $GITHUB_OUTPUT
+  #     if: env.LAUNCH_ID != ''
 
-  test-e2e-debug:
-    name: Test E2E UI (Debug)
-    runs-on: macos-15
-    if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    needs:
-      - allure_testops_launch
-      - build-test-app-and-frameworks
-    env:
-      LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
-    strategy:
-      matrix:
-        batch: [0, 1]
-      fail-fast: false
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: actions/download-artifact@v4
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/bootstrap
-      env:
-        INSTALL_ALLURE: true
-        INSTALL_YEETD: true
-        SKIP_SWIFT_BOOTSTRAP: true
-    - name: Run UI Tests (Debug)
-      run: bundle exec fastlane test_e2e_mock device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}' test_without_building:true
-      timeout-minutes: 100
-      env:
-        MATRIX_SIZE: ${{ strategy.job-total }}
-        STREAM_DEMO_APP_SECRET: ${{ secrets.STREAM_DEMO_APP_SECRET }}
-    - name: Allure TestOps Upload
-      if: env.LAUNCH_ID != '' && (success() || failure())
-      run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
-      env:
-        ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-    - name: Allure TestOps Launch Removal
-      if: env.LAUNCH_ID != '' && cancelled()
-      run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
-      env:
-        ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-    - name: Parse xcresult
-      if: failure()
-      run: |
-        brew install chargepoint/xcparse/xcparse
-        xcparse logs fastlane/test_output/StreamChatUITestsApp.xcresult fastlane/test_output/logs/
-    - uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: Test Data E2E
-        path: |
-          fastlane/recordings
-          fastlane/sinatra_log.txt
-          fastlane/test_output/logs/*/Diagnostics/**/*.txt
-          fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
+  # test-e2e-debug:
+  #   name: Test E2E UI (Debug)
+  #   runs-on: macos-15
+  #   if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   needs:
+  #     - allure_testops_launch
+  #     - build-test-app-and-frameworks
+  #   env:
+  #     LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
+  #   strategy:
+  #     matrix:
+  #       batch: [0, 1]
+  #     fail-fast: false
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/bootstrap
+  #     env:
+  #       INSTALL_ALLURE: true
+  #       INSTALL_YEETD: true
+  #       SKIP_SWIFT_BOOTSTRAP: true
+  #   - name: Run UI Tests (Debug)
+  #     run: bundle exec fastlane test_e2e_mock device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}' test_without_building:true
+  #     timeout-minutes: 100
+  #     env:
+  #       MATRIX_SIZE: ${{ strategy.job-total }}
+  #       STREAM_DEMO_APP_SECRET: ${{ secrets.STREAM_DEMO_APP_SECRET }}
+  #   - name: Allure TestOps Upload
+  #     if: env.LAUNCH_ID != '' && (success() || failure())
+  #     run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
+  #     env:
+  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #   - name: Allure TestOps Launch Removal
+  #     if: env.LAUNCH_ID != '' && cancelled()
+  #     run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
+  #     env:
+  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: |
+  #       brew install chargepoint/xcparse/xcparse
+  #       xcparse logs fastlane/test_output/StreamChatUITestsApp.xcresult fastlane/test_output/logs/
+  #   - uses: actions/upload-artifact@v4
+  #     if: failure()
+  #     with:
+  #       name: Test Data E2E
+  #       path: |
+  #         fastlane/recordings
+  #         fastlane/sinatra_log.txt
+  #         fastlane/test_output/logs/*/Diagnostics/**/*.txt
+  #         fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
 
-  build-apps:
-    name: Build Demo App + Example Apps
-    runs-on: macos-15
-    needs: build-test-app-and-frameworks
-    if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: actions/download-artifact@v4
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/ruby-cache
-    - uses: ./.github/actions/xcode-cache
-    - name: Build Demo App
-      run: bundle exec fastlane build_demo
-      timeout-minutes: 10
-    - name: Build iMessageClone App
-      run: bundle exec fastlane build_imessage_clone
-      timeout-minutes: 10
-    - name: Build SlackClone App
-      run: bundle exec fastlane build_slack_clone
-      timeout-minutes: 10
-    - name: Build MessengerClone App
-      run: bundle exec fastlane build_messenger_clone
-      timeout-minutes: 10
-    - name: Build YouTubeClone App
-      run: bundle exec fastlane build_youtube_clone
-      timeout-minutes: 10
+  # build-apps:
+  #   name: Build Demo App + Example Apps
+  #   runs-on: macos-15
+  #   needs: build-test-app-and-frameworks
+  #   if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/ruby-cache
+  #   - uses: ./.github/actions/xcode-cache
+  #   - name: Build Demo App
+  #     run: bundle exec fastlane build_demo
+  #     timeout-minutes: 10
+  #   - name: Build iMessageClone App
+  #     run: bundle exec fastlane build_imessage_clone
+  #     timeout-minutes: 10
+  #   - name: Build SlackClone App
+  #     run: bundle exec fastlane build_slack_clone
+  #     timeout-minutes: 10
+  #   - name: Build MessengerClone App
+  #     run: bundle exec fastlane build_messenger_clone
+  #     timeout-minutes: 10
+  #   - name: Build YouTubeClone App
+  #     run: bundle exec fastlane build_youtube_clone
+  #     timeout-minutes: 10
 
-  test-integration:
-    name: Test Integration
-    runs-on: macos-15
-    needs: build-test-app-and-frameworks
-    if: ${{ github.event.inputs.record_snapshots != 'true' }}
-    steps:
-    - uses: actions/checkout@v4.1.1
-    - uses: actions/download-artifact@v4
-      with:
-        name: cache-derived-data
-        path: derived_data/Build/
-    - uses: ./.github/actions/ruby-cache
-    - uses: ./.github/actions/xcode-cache
-    - name: Test SPM Integration
-      run: bundle exec fastlane spm_integration
-      timeout-minutes: 25
+  # test-integration:
+  #   name: Test Integration
+  #   runs-on: macos-15
+  #   needs: build-test-app-and-frameworks
+  #   if: ${{ github.event.inputs.record_snapshots != 'true' }}
+  #   steps:
+  #   - uses: actions/checkout@v4.1.1
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: cache-derived-data
+  #       path: derived_data/Build/
+  #   - uses: ./.github/actions/ruby-cache
+  #   - uses: ./.github/actions/xcode-cache
+  #   - name: Test SPM Integration
+  #     run: bundle exec fastlane spm_integration
+  #     timeout-minutes: 25
