Test

diff --git a/.github/workflows/smoke-checks.yml b/.github/workflows/smoke-checks.yml
--- a/.github/workflows/smoke-checks.yml
+++ b/.github/workflows/smoke-checks.yml
@@ -40,10 +40,7 @@ jobs:
       with:
         name: cache-derived-data
         path: |
-          derived_data/Build/**/*.app
-          derived_data/Build/**/*.xctestrun
-          derived_data/Build/**/*.framework
-          derived_data/Products/
+          derived_data/Build/
 
   # automated-code-review:
   #   name: Automated Code Review
@@ -109,6 +106,9 @@ jobs:
         ls derived_data/
         echo "ls derived_data/Build/"
         ls derived_data/Build/
+        ls derived_data/Build/Intermediates.noindex/
+        ls derived_data/Build/Products/
+        ls derived_data/Build/Products/Debug-iphonesimulator/
     - uses: ./.github/actions/bootstrap
       env:
         INSTALL_YEETD: true
@@ -205,67 +205,74 @@ jobs:
   #     run: echo "launch_id=${{env.LAUNCH_ID}}" >> $GITHUB_OUTPUT
   #     if: env.LAUNCH_ID != ''
 
-  # test-e2e-debug:
-  #   name: Test E2E UI (Debug)
-  #   runs-on: macos-14
-  #   if: ${{ github.event_name != 'push' && github.event.inputs.snapshots != 'true' }}
-  #   needs:
-  #     - test-llc-debug
-  #     - allure_testops_launch
-  #     - build-test-app-and-frameworks
-  #   env:
-  #     LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
-  #   strategy:
-  #     matrix:
-  #       batch: [0, 1]
-  #     fail-fast: false
-  #   steps:
-  #   - uses: actions/checkout@v4.1.1
-  #   - uses: actions/download-artifact@v4
-  #     with:
-  #       name: cache-derived-data
-  #       path: derived_data/Build/
-  #   - uses: ./.github/actions/bootstrap
-  #     env:
-  #       INSTALL_ALLURE: true
-  #       INSTALL_YEETD: true
-  #       SKIP_MINT_BOOTSTRAP: true
-  #       SKIP_BREW_BOOTSTRAP: true
-  #   - name: Run UI Tests (Debug)
-  #     run: bundle exec fastlane test_e2e_mock device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}' test_without_building:true
-  #     timeout-minutes: 100
-  #     env:
-  #       XCODE_VERSION: "15.0.1" # the most stable pair of Xcode
-  #       IOS_SIMULATOR_DEVICE: "iPhone 15 Pro (17.0)" # and iOS
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       GITHUB_PR_NUM: ${{ github.event.number }}
-  #       MATRIX_SIZE: ${{ strategy.job-total }}
-  #       STREAM_DEMO_APP_SECRET: ${{ secrets.STREAM_DEMO_APP_SECRET }}
-  #   - name: Allure TestOps Upload
-  #     if: env.LAUNCH_ID != '' && (success() || failure())
-  #     run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-  #   - name: Allure TestOps Launch Removal
-  #     if: env.LAUNCH_ID != '' && cancelled()
-  #     run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
-  #     env:
-  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-  #   - name: Parse xcresult
-  #     if: failure()
-  #     run: |
-  #       brew install chargepoint/xcparse/xcparse
-  #       xcparse logs fastlane/test_output/StreamChatUITestsApp.xcresult fastlane/test_output/logs/
-  #   - uses: actions/upload-artifact@v4
-  #     if: failure()
-  #     with:
-  #       name: Test Data E2E
-  #       path: |
-  #         fastlane/recordings
-  #         fastlane/sinatra_log.txt
-  #         fastlane/test_output/logs/*/Diagnostics/**/*.txt
-  #         fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
+  test-e2e-debug:
+    name: Test E2E UI (Debug)
+    runs-on: macos-14
+    if: ${{ github.event_name != 'push' && github.event.inputs.snapshots != 'true' }}
+    needs:
+      - test-llc-debug
+      - build-test-app-and-frameworks
+    # env:
+    #   LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
+    strategy:
+      matrix:
+        batch: [0]
+      fail-fast: false
+    steps:
+    - uses: actions/checkout@v4.1.1
+    - uses: actions/download-artifact@v4
+      with:
+        name: cache-derived-data
+        path: derived_data/
+    - run: |
+        echo "ls derived_data/"
+        ls derived_data/
+        echo "ls derived_data/Build/"
+        ls derived_data/Build/
+        ls derived_data/Build/Intermediates.noindex/
+        ls derived_data/Build/Products/
+        ls derived_data/Build/Products/Debug-iphonesimulator/
+    - uses: ./.github/actions/bootstrap
+      env:
+        INSTALL_ALLURE: false
+        INSTALL_YEETD: true
+        SKIP_MINT_BOOTSTRAP: true
+        SKIP_BREW_BOOTSTRAP: true
+    - name: Run UI Tests (Debug)
+      run: bundle exec fastlane test_e2e_mock device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}' test_without_building:true
+      timeout-minutes: 100
+      env:
+        XCODE_VERSION: "15.0.1" # the most stable pair of Xcode
+        IOS_SIMULATOR_DEVICE: "iPhone 15 Pro (17.0)" # and iOS
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GITHUB_PR_NUM: ${{ github.event.number }}
+        MATRIX_SIZE: ${{ strategy.job-total }}
+        STREAM_DEMO_APP_SECRET: ${{ secrets.STREAM_DEMO_APP_SECRET }}
+    # - name: Allure TestOps Upload
+    #   if: env.LAUNCH_ID != '' && (success() || failure())
+    #   run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+    # - name: Allure TestOps Launch Removal
+    #   if: env.LAUNCH_ID != '' && cancelled()
+    #   run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
+    #   env:
+    #     ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+    # - name: Parse xcresult
+    #   if: failure()
+    #   run: |
+    #     brew install chargepoint/xcparse/xcparse
+    #     xcparse logs fastlane/test_output/StreamChatUITestsApp.xcresult fastlane/test_output/logs/
+    # - uses: actions/upload-artifact@v4
+    #   if: failure()
+    #   with:
+    #     name: Test Data E2E
+    #     path: |
+    #       fastlane/recordings
+    #       fastlane/sinatra_log.txt
+    #       fastlane/test_output/logs/*/Diagnostics/**/*.txt
+    #       fastlane/test_output/logs/*/Diagnostics/simctl_diagnostics/DiagnosticReports/*
 
   # build-apps:
   #   name: Build Demo App + Example Apps
