Test

diff --git a/.github/workflows/smoke-checks.yml b/.github/workflows/smoke-checks.yml
--- a/.github/workflows/smoke-checks.yml
+++ b/.github/workflows/smoke-checks.yml
@@ -85,84 +85,84 @@ jobs:
   #       MATRIX_CONTEXT: ${{ toJson(matrix) }}
   #     if: ${{ github.event_name == 'push' && failure() }}
 
-  # build-and-test-ui-debug:
-  #   name: Test UI (Debug)
-  #   runs-on: macos-12
-  #   if: ${{ github.event_name != 'push' }}
-  #   steps:
-  #   - uses: actions/checkout@v3.1.0
-  #   - run: ls StreamChat.xcodeproj/**/Package.resolved || true
-  #   - uses: ./.github/actions/bootstrap
-  #     env:
-  #       INSTALL_XCPARSE: true
-  #   - name: Run UI Tests (Debug)
-  #     run: bundle exec fastlane test_ui device:"${{ env.IOS_SIMULATOR_DEVICE }}"
-  #     timeout-minutes: 25
-  #     env:
-  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       GITHUB_PR_NUM: ${{ github.event.number }}
-  #   - name: Parse xcresult
-  #     if: failure()
-  #     run: xcparse screenshots fastlane/test_output/StreamChatUI.xcresult fastlane/test_output/snapshots --test
-  #   - uses: actions/upload-artifact@v3
-  #     if: failure()
-  #     with:
-  #       name: Test Data
-  #       path: |
-  #         fastlane/test_output/snapshots
-
-  build-and-test-e2e-debug:
-    name: Test E2E UI (Debug)
+  build-and-test-ui-debug:
+    name: Test UI (Debug)
     runs-on: macos-12
-    # if: ${{ github.event_name != 'push' }}
-    # needs: allure_testops_launch
-    # env:
-    #   LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
-    # strategy:
-    #   matrix:
-    #     batch: [0, 1, 2]
-    #   fail-fast: false
+    if: ${{ github.event_name != 'push' }}
     steps:
     - uses: actions/checkout@v3.1.0
-      # if: env.LAUNCH_ID != ''
+    - run: ls StreamChat.xcodeproj/**/Package.resolved || true
     - uses: ./.github/actions/bootstrap
-      # if: env.LAUNCH_ID != ''
-      # env:
-        # INSTALL_ALLURE: true
-        # INSTALL_XCPARSE: true
+      env:
+        INSTALL_XCPARSE: true
     - name: Run UI Tests (Debug)
-      # if: env.LAUNCH_ID != ''
-      run: bundle exec fastlane test_e2e_mock cron:true device:"iPhone 14 Pro Max" ios:latest
-      timeout-minutes: 40
+      run: bundle exec fastlane test_ui device:"${{ env.IOS_SIMULATOR_DEVICE }}"
+      timeout-minutes: 25
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GITHUB_PR_NUM: ${{ github.event.number }}
-        MATRIX_SIZE: ${{ strategy.job-total }}
-        STREAM_DEMO_APP_SECRET: ${{ secrets.STREAM_DEMO_APP_SECRET }}
 
     - run: ls StreamChat.xcodeproj/**/Package.resolved || true
-    # - name: Allure TestOps Upload
-    #   if: env.LAUNCH_ID != '' && (success() || failure())
-    #   run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #     ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
-    # - name: Allure TestOps Launch Removal
-    #   if: env.LAUNCH_ID != '' && cancelled()
-    #   run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
-    #   env:
-    #     ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
     # - name: Parse xcresult
     #   if: failure()
-    #   run: xcparse logs fastlane/test_output/StreamChatUITestsApp.xcresult fastlane/test_output/logs/
+    #   run: xcparse screenshots fastlane/test_output/StreamChatUI.xcresult fastlane/test_output/snapshots --test
     # - uses: actions/upload-artifact@v3
     #   if: failure()
     #   with:
     #     name: Test Data
     #     path: |
-    #       fastlane/recordings
-    #       fastlane/sinatra_log.txt
-    #       fastlane/test_output/logs/*/Diagnostics/StreamChatUITestsAppUITests-*/*/*.txt
+    #       fastlane/test_output/snapshots
+
+  # build-and-test-e2e-debug:
+  #   name: Test E2E UI (Debug)
+  #   runs-on: macos-12
+  #   if: ${{ github.event_name != 'push' }}
+  #   needs: allure_testops_launch
+  #   env:
+  #     LAUNCH_ID: ${{ needs.allure_testops_launch.outputs.launch_id }}
+  #   strategy:
+  #     matrix:
+  #       batch: [0, 1, 2]
+  #     fail-fast: false
+  #   steps:
+  #   - uses: actions/checkout@v3.1.0
+  #     if: env.LAUNCH_ID != ''
+  #   - uses: ./.github/actions/bootstrap
+  #     if: env.LAUNCH_ID != ''
+  #     env:
+  #       INSTALL_ALLURE: true
+  #       INSTALL_XCPARSE: true
+  #   - name: Run UI Tests (Debug)
+  #     if: env.LAUNCH_ID != ''
+  #     run: bundle exec fastlane test_e2e_mock device:"${{ env.IOS_SIMULATOR_DEVICE }}" batch:'${{ matrix.batch }}'
+  #     timeout-minutes: 40
+  #     env:
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       GITHUB_PR_NUM: ${{ github.event.number }}
+  #       MATRIX_SIZE: ${{ strategy.job-total }}
+  #       STREAM_DEMO_APP_SECRET: ${{ secrets.STREAM_DEMO_APP_SECRET }}
+  #   - name: Allure TestOps Upload
+  #     if: env.LAUNCH_ID != '' && (success() || failure())
+  #     run: bundle exec fastlane allure_upload launch_id:$LAUNCH_ID
+  #     env:
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #   - name: Allure TestOps Launch Removal
+  #     if: env.LAUNCH_ID != '' && cancelled()
+  #     run: bundle exec fastlane allure_launch_removal launch_id:$LAUNCH_ID
+  #     env:
+  #       ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
+  #   - name: Parse xcresult
+  #     if: failure()
+  #     run: xcparse logs fastlane/test_output/StreamChatUITestsApp.xcresult fastlane/test_output/logs/
+  #   - uses: actions/upload-artifact@v3
+  #     if: failure()
+  #     with:
+  #       name: Test Data
+  #       path: |
+  #         fastlane/recordings
+  #         fastlane/sinatra_log.txt
+  #         fastlane/test_output/logs/*/Diagnostics/StreamChatUITestsAppUITests-*/*/*.txt
 
   # allure_testops_launch:
   #   name: Launch Allure TestOps
